### ISSUE TITLE
k8s 部署 kafka 踩坑

### ISSUE THREAD

**Issue by Draymonders** [Draymonders/Code-Life#10]
- `kafka`依赖`zookeeper`
- 所以也要部署`zookeeper`

**Comment by Draymonders** [comment]
具体的文件如下
- [zookeeper-service](https://github.com/Draymonders/Code-Life/blob/master/middleware/k8s/service/zookeeper-service.yml)
- [zookeeper-deployment](https://github.com/Draymonders/Code-Life/blob/master/middleware/k8s/deployment/zookeeper-deployment.yml)
- [kafka-service](https://github.com/Draymonders/Code-Life/blob/master/middleware/k8s/service/kafka-service.yml)
- [kafka-deployment](https://github.com/Draymonders/Code-Life/blob/master/middleware/k8s/deployment/kafka-deployment.yml)

**Comment by Draymonders** [comment]
部署顺序是 先`zookeeper-service`和`kafka-service`

然后部署`zookeeper-deployment`和`kafka-deployment`

**Comment by Draymonders** [comment]
# 中间遇到的问题

## kafka env配置
- `KAFKA_ADVERTISED_HOST_NAME` 是指kafka对外访问的地址  此处应该传`kafka-service`暴露的`cluster-ip`

- `KAFKA_ZOOKEEPER_CONNECT` 是指zookeeper的地址

## 部署完以后一直报错 CrashBack
然后就不知所措了， 持续了一天
然后通过`kubectl describe pod kafka-xxxx`，看到了`containerId`,  来到了擅长的`docker`, 遂`docker logs contianerId`  

发现错误如下
```
org.apache.kafka.common.config.ConfigException: Invalid value tcp://10.102.205.143:9092 for configuration port: Not a number of type INT
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:726)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:142)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1119)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1122)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1102)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29)
	at kafka.Kafka$.main(Kafka.scala:68)
	at kafka.Kafka.main(Kafka.scala)
```

报错是 `port`是`int`, 但是传入了`tcp://10.102.205.143:9092`

经过查询， 发现如这里所说 https://github.com/wurstmeister/kafka-docker/issues/122

```
Seems that if you have service called kafka, kubernetes creates environment variable called KAFKA_PORT="tcp://x.x.x.x:9092"
```

就是部署了一个`service`叫`kafka` 然后环境变量里面`kakfa-port: tcp://x.x.x.x:9092`导致的问题
### 解决方案
知道了问题所在, 把`kafka-service`的`name`从原来的`kafka`换成了`kafka-xxx` 

问题解决

**Comment by Draymonders** [comment]
# 测试是否部署成功
## 1. 安装KafkaCat
```
sudo apt-get install kafkacat
```

## 2. 建立生产者关联对应 topic
```
kafkacat -b ${kafka_service_ip:port} -t ${topic_name} -p
```

## 3. 建立消费者关联对应 topic
新开一个`terminal`
```
kafkacat -b ${kafka_service_ip:port} -t ${topic_name}
```

## 4. 在生产者处随便输入， 看消费者端能否接收到信息
如果能接收到输入的信息，那么部署成功.

**Comment by Draymonders** [comment]
# 参考文章
- [如何於Kubernetes上佈建Apache Kafka Cluster運行環境
](https://tpu.thinkpower.com.tw/tpu/articleDetails/1359)

**Comment by 492162921** [comment]
_在k8s中使用kafka做实验，刚好解决我的遇到的“ Not a number of type INT ”问题，感谢分享。_
